server:
  port: 8000
  servlet:
    context-path: /kdagg
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kda?serverTimezone=Asia/Seoul
    username: park
    password: park2024
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
         hibernate:
            format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  